name: aria2c
description: "Use dart and aria2c to connect websocket for JsonRPC communication."
version: 0.0.5
homepage: https://github.com/pgfeng/aria2c

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  web_socket_client: ^0.1.5

dev_dependencies:
  test: ^1.24.8